language: python
python:
  - "3.9"
before_install:
  - cd mysite
install:
  - pip install -r requirements.txt
  - python manage.py migrate
script:
  - black --check blogging mysite polling
  - python manage.py test