# Use a specific version of the Python image
FROM python:3.9

# Set the working directory
WORKDIR /data/mysite

# Copy only the requirements.txt file
COPY mysite/requirements.txt .

# Upgrade pip and setuptools, install requirements, and clean up in one layer
RUN pip install --upgrade pip setuptools && \
    pip install --no-cache-dir -r requirements.txt && \
    rm requirements.txt
